# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

# NPM install dependencias de Javascript
steps:
- task: Npm@1
  displayName: '[Frontend] Instala dependencias NPM'
  inputs:
    workingDir: 'InstaViajes_frontend'
    verbose: false

# Compilación de la aplicación Javascript  
- task: Npm@1
  displayName: '[Frontend] Compila la aplicación vite'
  inputs:
    command: custom
    workingDir: 'InstaViajes_frontend'
    verbose: false
    customCommand: 'run build'

- task: DownloadSecureFile@1
  name: env_file
  inputs:
    secureFile: 'instaviajes_laravel_env_file'

- script: cp -f $(env_file.secureFilePath) InstaViajes_backend/.env
  displayName: '[Backend] Copia archivo .env de Laravel'

- task: Docker@2
  displayName: '[Backend] Build and push Docker Image'
  inputs:
    containerRegistry: 'Insta-Dockers Registry service connection'
    repository: 'instaviajes-backend'
    command: 'buildAndPush'
    Dockerfile: 'dockers/backend/production_deploy/Dockerfile'
    buildContext: '$(Build.Repository.LocalPath)'

- task: Docker@2
  displayName: '[Frontend] Build and push Docker Image'
  inputs:
    containerRegistry: 'Insta-Dockers Registry service connection'
    repository: 'instaviajes-frontend'
    command: 'buildAndPush'
    Dockerfile: 'dockers/frontend/production_deploy/Dockerfile'
    buildContext: '$(Build.Repository.LocalPath)'

- task: SSH@0
  inputs:
    sshEndpoint: 'InstaviajesDocker'
    runOptions: 'commands'
    commands: |
      az acr login --name instadockersregistry;
      docker stop instaviajes-frontend;
      docker rm instaviajes-frontend;
      docker pull instadockersregistry.azurecr.io/instaviajes-frontend:latest;
      docker pull instadockersregistry.azurecr.io/instaviajes-backend:latest;
      docker run --name instaviajes-frontend -d -p 80:80 instadockersregistry.azurecr.io/instaviajes-frontend
      docker run --name instaviajes-backend -d -p 3000:80 instadockersregistry.azurecr.io/instaviajes-backend

    readyTimeout: '20000'